PATIENT_START_TAG='<P>'
PATIENT_END_TAG='</P>'
THERAPIST_START_TAG='<T>'
THERAPIST_END_TAG='</T>'
UTTER_START_TAG='<U>'
UTTER_END_TAG='</U>'

special_speaker_tags = [PATIENT_START_TAG, PATIENT_END_TAG, THERAPIST_START_TAG, THERAPIST_END_TAG, UTTER_START_TAG, UTTER_END_TAG]
